<?php

/**
 * hook_mail_alter()
 **/
function sneharts_common_mail_alter(&$message) {
//figure out the message id or the key of your email
  $language = $message['language'];
  $account= array('user' => $message['params']['account']);
	if ($message['key'] == 'notify_ec_user') {
		$message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
	}


	switch ($message['key']) {

        case 'register_no_approval_required':
   
          unset($message['body']);
    
          $text = theme('register_no_approval_required', array('message' => $message));
          $message['body'][0] =  token_replace($text, $account, array('language' => $language , 'callback' => 'user_mail_tokens', 'sanitize' => FALSE, 'clear' => TRUE)); 
        break;  

		case 'register_admin_created':
				$message['body'][0] =  theme('register_admin_created', array('message' => $message)); 

			break;

		case 'register_pending_approval':
			$message['body'][0] =  theme('register_pending_approval', array('message' => $message)); 
			break;

		case 'password_reset':
			$message['body'][0] =  theme('password_reset', array('message' => $message)); 
			break;	

		case 'status_activated':
			$message['body'][0] =  theme('status_activated', array('message' => $message)); 
			break;
		
		case 'status_blocked':
			$message['body'][0] =  theme('status_blocked', array('message' => $message)); 
			break;				

		case 'cancel_confirm':
			$message['body'][0] =  theme('cancel_confirm', array('message' => $message)); 
			break;

		case 'status_canceled':
			$message['body'][0] =  theme('status_canceled', array('message' => $message)); 
			break;	

		default:
			
			break;
	}
}

function sneharts_common_theme($existing, $type, $theme, $path) {
  return array(
    'register_admin_created' => array(
      'variables' => array('message' => NULL),
      'template' => 'register-admin-created',
      'path' => drupal_get_path('module', 'sneharts_common') . '/templates',
    ),
    'register_no_approval_required' => array(
      'variables' => array('message' => NULL),
      'template' => 'register-no-approval-required',
      'path' => drupal_get_path('module', 'sneharts_common') . '/templates',
    ),
    'register_pending_approval' => array(
      'variables' => array('message' => NULL),
      'template' => 'register-pending-approval',
      'path' => drupal_get_path('module', 'sneharts_common') . '/templates',
    ),
    'password_reset' => array(
      'variables' => array('message' => NULL),
      'template' => 'password-reset',
      'path' => drupal_get_path('module', 'sneharts_common') . '/templates',
    ),
    'status_activated' => array(
      'variables' => array('message' => NULL),
      'template' => 'status-activated',
      'path' => drupal_get_path('module', 'sneharts_common') . '/templates',
    ),
    'status_blocked' => array(
      'variables' => array('message' => NULL),
      'template' => 'status-blocked',
      'path' => drupal_get_path('module', 'sneharts_common') . '/templates',
    ),
    'cancel_confirm' => array(
      'variables' => array('message' => NULL),
      'template' => 'cancel-confirm',
      'path' => drupal_get_path('module', 'sneharts_common') . '/templates',
    ),
    'status_canceled' => array(
      'variables' => array('message' => NULL),
      'template' => 'status-canceled',
      'path' => drupal_get_path('module', 'sneharts_common') . '/templates',
    ),
  );
}